#pragma once
// 库函数
#include "Arduino.h"
#include "SimpleFOC.h"
// 模块头文件
#include "my_motion.h"
// 模块内头文件
#include "my_mpu6050.h"
#include "my_foc.h"
#include "my_sms.h"
#include "my_bat.h"
// 全局头文件
#include "my_io.h"
#include "my_config.h"
#include "my_tool.h"
// 结构体定义

void test_mode();
void fall_check();
void robot_pos_control();
void pitch_control();
void robot_state_update();
void yaw_control();
void vel_control();
void torque_add();
void leg_update();